### ISSUE TITLE
question in "Real-time Transformer-based Open-Vocabulary Detection with Efficient Fusion Head"

### ISSUE THREAD

**Issue by shuchang0714** [om-ai-lab/OmDet#1]
Hello, author, your work is excellent. I have a question about tensorrt-groundingdino on your paper "Real-time Transformer-based Open-Vocabulary Detection with Efficient Fusion Head", I can only convert gd in tensorrt-fp32 by trtexec which is around 90ms on A100, could you share your menthod on how to convert gd to tensorrt? Thank you.

**Comment by ccsvd** [comment]
have the same question.

**Comment by P3ngLiu** [comment]
We have updated a ReadMe to explain how we converted the grounding dino to TensorRT. [cvt_grounding_dino-en.md](https://github.com/om-ai-lab/OmDet/blob/main/docs/cvt_grounding_dino-en.md) Feel free to ask any other questions about this.
