### ISSUE TITLE
Is there a way to export onnx similar to yolo-world

### ISSUE THREAD

**Issue by GallonDeng** [om-ai-lab/OmDet#16]
nice work! Is there a way to export onnx both text backbone and omdet, similar to yolo-world?

**Comment by hx621** [comment]
@AllenDun   Yes， i think it just like we described in the README for converting Grounding DINO

**Comment by GallonDeng** [comment]
Thanks, so there could be a demo for this? The 'export.py' cannot directly do this right?

**Comment by hx621** [comment]
We currently do not have plans to provide such a demo. However, I believe you can build a similar demo based on the export.py.
