### ISSUE TITLE
Model Conversion

### ISSUE THREAD

**Issue by mohd-adnaan** [om-ai-lab/OmDet#18]
Hi, I am trying to convert the .py model to coreML form , but couldn't succeeded and then after converting the model successfully to ONNNX form , still can't convert the model in coreML to use in an IOS application. Kindly direct me to do the same.

Thanks and Regards

**Comment by hx621** [comment]
@mohd-adnaan Sorry,  we're not experts in this particular area. If you've completed this task, we would greatly appreciate it if you could share your experience here to help others in need."
