### ISSUE TITLE
Batched MultiHeadAttention

### ISSUE THREAD

**Issue by yonigozlan** [om-ai-lab/OmDet#19]
Hi! Yoni from Hugging Face again.
I'm opening a separate issue because there seems to be a potentially important problem in the model's encoder.

https://github.com/om-ai-lab/OmDet/blob/542ce974ee22e16f9e532500e3f84e4702c03abf/omdet/omdet_v2_turbo/ela_encoder.py#L27

Shouldn't this MultiHeadAttention be initialized with `batch_first=True`, as the inputs of the self_attn layer are of the shape (batch_size, ...)? This causes inconsistencies when using the model for batch inference. 

Thanks for your consideration!

**Comment by hx621** [comment]
@yonigozlan I have checked the code, and it should be batch_first=True.

**Comment by P3ngLiu** [comment]
@yonigozlan This is indeed an error in the inference code. Thank you very much for your reminder. We just pushed an update and change it to batch_first=True.

**Comment by yonigozlan** [comment]
Great! Are you planning on pushing updated weights as well? Or are the weights correct with this change?

**Comment by P3ngLiu** [comment]
The current weights are correct with this change, so no update is needed.
