### ISSUE TITLE
OinW35@mAP=30.1

### ISSUE THREAD

**Issue by jetyingjia** [om-ai-lab/OmDet#2]
关于Oinw35@mAP=30.1有些疑问：
1、在OmDetv2中(2024的IET CV)这篇文章中，ConvNext-B的性能是20.9，此篇文章性能为30.1(模型较小但是SOTA)，性能差异较大，是否出现了笔误？

**Comment by P3ngLiu** [comment]
您好，并不是笔误。OmDet-Turbo相较于OmDetV2取得了较大的性能提升，主要得益于两个原因：
1. 我们加入了更多的训练数据和更长的训练时间。
2. 更统一的Multi-task Learning 策略。
3. 新的DINO结构本身比OmDetV2的Sparse-RCNN架构更有优势。
我们的分数也更新到了[ODinW leaderboard](https://eval.ai/web/challenges/challenge-page/1839/leaderboard/4317)

**Comment by Baboom-l** [comment]
我感觉是调过prompt
