### ISSUE TITLE
请问有TensorRT版本的GroundingDino可以分享吗？

### ISSUE THREAD

**Issue by levylll** [om-ai-lab/OmDet#20]
碰巧看到您有GroundingDino导出为TensorRT的分享
想问一下您那边有FP32 的tensorRT版本的GroundingDino分享一下吗？

**Comment by hx621** [comment]
@levylll 由于在omdet的工作中，我们主要和Grounding DINO 的trt 版本 进行性能对比， 针对Grounding DINO的 trt 版本的精度测试 并不完整。因此本着严谨的态度，暂时没有将此部分工作进行开源。 如果您在模型转换过程中遇到任何问题，我们很乐意与您一起探讨解决
