### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by ccsvd** [om-ai-lab/OmDet#3]
hi, this is a good job.
do you have the plan to release the train code???

**Comment by P3ngLiu** [comment]
Thank you for your interest in our project. Currently, we don't have plans to open-source the training code. However, we will be open-sourcing some more powerful and larger pre-trained model weights in the future. Please continue to follow our GitHub for updates.

**Comment by ccsvd** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
