### ISSUE TITLE
About OmDet-Turbo-Base

### ISSUE THREAD

**Issue by zhangpzh** [om-ai-lab/OmDet#4]
It is glad to see your work OmDet-Turbo that I have used GroundingDINO for so long. It seems on some datasets, OmDet-Turbo-Base is competitive. However, currently it seems only the Swin-Tiny-based version is released. How about OmDet-Turbo-Base ?

**Comment by P3ngLiu** [comment]
The OmDet-Turbo-Base model is not avaibale for now, but we are planned to release a OmDet-Turbo-Base checkpoints later. We will update the README with the checkpoint url as soon as it's available!
