### ISSUE TITLE
关于预测和训练

### ISSUE THREAD

**Issue by lkxxxxx** [om-ai-lab/OmDet#5]
您好作者，我对您的研究非常感兴趣，但是我遇到了一些问题，需要您的解答：
1.请问一下在使用模型预测时能否不设定词汇表,像yolo-world那样直接预测图片。或者说我如何查看clip的词汇表里面是否有我需要检测的目标？
2.能否使用自己的预训练clip权重并使用自己的数据集训练OmDet模型吗？
非常感谢解答！

**Comment by snakeztc** [comment]
1. 词表可以预设，比如设定COCO或者O365的词表，就可以直接输出
2. 可以换别的CLIP模型，但这样意味着模型需要重新预训练

**Comment by lkxxxxx** [comment]
好的，非常感谢
