### ISSUE TITLE
How to convert to onnx

### ISSUE THREAD

**Issue by lyffly** [om-ai-lab/OmDet#9]
awesome work!!
can you provide sample code  to convert pytorch to onnx ？

**Comment by P3ngLiu** [comment]
Thank you for your interest in our project! No problem, we will update the sample code for converting ONNX soon.

**Comment by hx621** [comment]
> awesome work!! can you provide sample code to convert pytorch to onnx ？



> awesome work!! can you provide sample code to convert pytorch to onnx ？

We have just added support for ONNX model conversion. Please check README.md  for more details.

**Comment by hx621** [comment]
@lyffly We have just added support for ONNX model conversion. Please check README.md for more details.
